### PR TITLE
Driver tsm02

### PR DESCRIPTION
**Pull request by mnederlof**
Integrating in TSM01 driver, as Z-Wave identifier is the same.

Also updating the way configuration updates are delivered to the device (which might move to the ZwaveDriver eventually / hopefully.

### CODE REVIEW

**Comment by caseda** [comment]
Thank you for your hard work.
but i'm sorry, i'm not going to accept this pull request, just contains too much custom code to "circumvent" of that 80% is already implemented

IE: configuration is already only send when the sensor is awake, if not it will get resend after ** seconds
this is taken care of in the core after the SET() command (so not in the z-wave drivers)
and can make use of Polling if needed, but since the "lights on/off" is not necessary in the case of homey, made that the default on/off for motion
was already busy converting all custom code, to already implemented/used code:
https://github.com/caseda/com.tkbhome/tree/TSP01/TSM02_test_driver

just don't wanna remember to change all this code if there is a change in the core somewhere.
or if there is a z-wave driver capability change.

**Comment by mnederlof** [comment]
Well that is ok, i'll check your work after you're finished :)

@configuration: It is just that the update settings never worked for me, and at least that way it worked flawlessly. Also i've never seen the the homey core resend the SET command, that's why i made the workaround of waiting for it to send a WAKE report, to send the settings (which works awesome on the TSP01).

Also, i see you've added the BINARY_SENSOR_GET commands, but i've never seen them work. (they always timeout or just don't work...), that is why i've not added them in the code i sent you.

**Comment by mnederlof** [comment]
I do want to point out the changes i made in the measure_luminance and measure_temperature though, as this is now using the Zwave reported level spec. Also the TSP01 is sending a luminance percentage (as specified in the report it sends), where the specs of the device say that it can detect the range of 0 - 500 Lux.

I hope you can incorporate that so it will give back a proper temperature and lux value to the Homey.

**Comment by caseda** [comment]
true, most GET's only work when the sensor is awake, i'll think about if adding "getOnAwake" tag will make any difference in that.
but you are probably right about it not having much sense, since it will (only?) get send when motion is detected

Temperature already fixed with the defaultConfig
and luminance = percentage of the GET scale = 0
need to change the GET to scale = 1 to fix it,
only now noticing it's not even implemented in the code 😅

**Comment by caseda** [comment]
and true about the parameters not send to the device properly, but not all devices use the wake_up_notification command to say its awake, so i don't think it will be implemented this way in the z-wave driver.

have already an [issue](https://github.com/athombv/homey/issues/1049) about this for some time now, and a new one was [created](https://github.com/athombv/homey/issues/1145) not too long ago which is the same

there is a work-a-round for now to have the sensor awake before saving it, which works 100% of the time. but definitely needs to be fixed in the core.

**Comment by mnederlof** [comment]
I can imagine not all devices use the wake_up_notification, though during initialization, all supported commands are queried by the zwave core i guess, so it could be surrounded by an if-statement checking if there that command is actually present in the device... (but since my code was monkeypatched for the tsp01 driver only i did not do that right now)

**Comment by caseda** [comment]
there is an actual callback from the sensor if parameters have been set inside the device `ACK`,
now homey empties its parameter queue even if the device gives back the `NO_ACK` call

there is 2 ways a battery device can be "awake" when it is sending stuff like motion, which does not always mean it can accept parameter changes, if this is the case the sensor usually sends the 'NO_ACK' callback.
and if the sensor is awake on it's wake up interval (or manual wake-up), then the sensor does always accept parameters, and then also the `ACK` callback for parameter changes.

have been debugging the hell out of this issue to get athom (in special emile) to understand what was going on 😅

**Comment by mnederlof** [comment]
That is indeed exactly what i experienced :)

**Comment by caseda** [comment]
i have updated my driver branch, if you would be so kind to test it ❤️

and let's see if it responds to the GET for luminance to report in lux or just times out on it (TKB for the win with just ignoring GET calls),
otherwise maybe thinking about creating a custom capability for luminance percentage instead of just multiplying it by 5, i don't think it works fully that way 😱

**Comment by mnederlof** [comment]
just installed new driver, initial output:

```
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Door/Window' } err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
  Properties1: { Scale: 1 } } err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Motion' } err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Temperature (version 1)',
  Properties1: { Scale: 0 } } err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Tamper' } err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug] node.on('online') arguments: { '0': false }
```

Will test more later, when i'll re-pair the device.

**Comment by mnederlof** [comment]
If i manually trigger a 'WAKE_UP_NOTIFICATION' (by pressing either the tamper button or the button inside), then the GET functions work:

```
[debug] node.on('online') arguments: { '0': true }
[debug] node.CommandClass['COMMAND_CLASS_WAKE_UP'].on('report') arguments: { '0': { value: 7, name: 'WAKE_UP_NOTIFICATION' },
  '1': {},
  '2': null }
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Door/Window' } err: null result: { 'Sensor Value (Raw)': <Buffer 00>,
  'Sensor Value': 'idle',
  'Sensor Type (Raw)': <Buffer 0a>,
  'Sensor Type': 'Door/Window' }
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
  Properties1: { Scale: 1 } } err: null result: { 'Sensor Type (Raw)': <Buffer 03>,
  'Sensor Type': 'Luminance (version 1)',
  'Level (Raw)': <Buffer 01>,
  Level: { Size: 1, Scale: 0, Precision: 0 },
  'Sensor Value': <Buffer 08>,
  'Sensor Value (Parsed)': 8 }
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Motion' } err: null result: { 'Sensor Value (Raw)': <Buffer ff>,
  'Sensor Value': 'detected an event',
  'Sensor Type (Raw)': <Buffer 0c>,
  'Sensor Type': 'Motion' }
[debug] node.on('online') arguments: { '0': true }
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Door/Window' } err: null result: { 'Sensor Value (Raw)': <Buffer ff>,
  'Sensor Value': 'detected an event',
  'Sensor Type (Raw)': <Buffer 0c>,
  'Sensor Type': 'Motion' }
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Luminance (version 1)',
  Properties1: { Scale: 1 } } err: null result: { 'Sensor Type (Raw)': <Buffer 03>,
  'Sensor Type': 'Luminance (version 1)',
  'Level (Raw)': <Buffer 01>,
  Level: { Size: 1, Scale: 0, Precision: 0 },
  'Sensor Value': <Buffer 01>,
  'Sensor Value (Parsed)': 1 }
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Temperature (version 1)',
  Properties1: { Scale: 0 } } err: null result: { 'Sensor Type (Raw)': <Buffer 01>,
  'Sensor Type': 'Temperature (version 1)',
  'Level (Raw)': <Buffer 0a>,
  Level: { Size: 2, Scale: 1, Precision: 0 },
  'Sensor Value': <Buffer 00 47>,
  'Sensor Value (Parsed)': 71 }
[debug]  COMMAND_CLASS_SENSOR_MULTILEVEL SENSOR_MULTILEVEL_GET args: { 'Sensor Type': 'Temperature (version 1)',
  Properties1: { Scale: 0 } } err: null result: { 'Sensor Type (Raw)': <Buffer 01>,
  'Sensor Type': 'Temperature (version 1)',
  'Level (Raw)': <Buffer 22>,
  Level: { Size: 2, Scale: 0, Precision: 1 },
  'Sensor Value': <Buffer 00 e1>,
  'Sensor Value (Parsed)': 22.5 }
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Tamper' } err: null result: { 'Sensor Value (Raw)': <Buffer 00>,
  'Sensor Value': 'idle',
  'Sensor Type (Raw)': <Buffer 08>,
  'Sensor Type': 'Tamper' }
[debug] node.on('online') arguments: { '0': false }
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Motion' } err: { [Error: timeout] message: 'timeout' } result: null
[debug]  COMMAND_CLASS_SENSOR_BINARY SENSOR_BINARY_GET args: { 'Sensor Type': 'Tamper' } err: { [Error: TRANSMIT_COMPLETE_NO_ACK] message: 'TRANSMIT_COMPLETE_NO_ACK' } result: null
[debug] node.on('online') arguments: { '0': false }
```

But that needs the same workaround / fix in the z-wave driver where it can only send data when a wake-up-notification has been received.

**Comment by mnederlof** [comment]
What i see with the luminance-get, is that the scale is being ignored... So still a percentage, instead of a Lux amount.

**Comment by mnederlof** [comment]
See my other remarks in the commits as defined in #9

**Comment by caseda** [comment]
thanks for the debug,

i've already made an [PR](https://github.com/athombv/node-homey-zwavedriver/pull/18) (/ discusion :D ) in the z-wave driver to have settings usable in driver only.
this will make it into the z-wave driver pretty soon and makes it unnecessary to monkey-patch the settings

questioning your decision of why'ed you want to cancel motion alarm more then 1016 seconds (which is 17 minutes) though.. since this is only 17 minutes after no motion is detected anymore, also possible by other means in homey (countdown app)

**Comment by mnederlof** [comment]
Well, because i also switch on/off light with the sensor in my living room. When we're watching a movie it happens sometimes that even with a timeout of 30 mins, the lights are turned off, because all of us are sitting still... So that is why i need a bigger timeout value.

**Comment by caseda** [comment]
So, also very easy doable with the countdown app :wink:
Which has no limits of counting, and has checks for it if Is still running for example. 

But just my 2 cents, things like lighting in the living room (space where you are 80% of the time) only should turn off if you really are away, not with just 30 minutes of no movement. 
It drains Battery like crazy when constantly seeing motion

**Comment by mnederlof** [comment]
Ah yes, i'll give it a go :)

**Comment by mnederlof** [comment]
Ok, removed that part of the code again, Countdown app is working like a charm 😄

**Comment by caseda** [comment]
i've update the driver to your debug log and what you wanted in your PR, did not use your full pr though 😜 since i wanted to change more anyway.

now the temp and lux also are gotten from the sensor on wake-up interval, and not just on motion, like the sensor did previously, for if the sensor is not triggered for a longer periode of time. (even though i'm not sure what the wakeup interval is on, by default).

**Comment by mnederlof** [comment]
checkout my pull request at https://github.com/athombv/node-homey-zwavedriver/pull/19
This fixes the incorrect bind of reports to a pending GET command request to the device.

We will see how that suggestion goes...

**Comment by caseda** [comment]
i think we are getting there with the last few changes i did to the driver though :p
if you think it's good enough
(at least until z-wave driver has been updated we can work around the issues by just waking up the sensor before saving)
i'll add it to the master branch and up for app-store tomorrow.

**Comment by caseda** [comment]
now is only waiting for the confirmation that the driver is as it should 😄 then i can send in the many added devices update to the store (actually all devices with the same id's... does make the app nice and small)

**Comment by mnederlof** [comment]
Have not tested it though (will try later tonight), but i noticed you changed the defaultConfiguration for temp and luminance auto-report-interval. What made you do that? (and have you also updated the defaults in the device's settings page?)

**Comment by caseda** [comment]
i changed it from 6 hours to 2 hours since, if there is no motion for longer then 6 hours, then the 6 hour mark is just too much for lux and temp reporting. and of course i changed that in the settings as well 😄 (just forgot to copy it over into this branch as wel :blush: )
(btw i removed the "on awake", because of this reason as well, saves more battery then getting it every awake)

**Pull request closed without merging**
